# Generated by Django 3.2.4 on 2021-06-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='EdificiosInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEI', models.CharField(max_length=35)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=60)),
                ('contacto', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadMaxima', models.IntegerField(default=8)),
                ('estadoCantidad', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateTimeField(auto_now=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Playas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('ubicacion', models.CharField(max_length=50)),
                ('imagePlay', models.URLField(blank=True, default='https://i.ibb.co/dQn81QZ/playa-default.png', null=True)),
                ('departamentos', models.CharField(max_length=45, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.estado')),
            ],
        ),
        migrations.CreateModel(
            name='TiposEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTE', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id_TrabajadoresDNI', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=35)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField()),
                ('celular', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('imageUser', models.URLField(blank=True, default='https://i.ibb.co/2tshgPv/andres-gevara.jpg', null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_UsuarioDNI', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('temperatura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubPlayas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('capacidad', models.IntegerField()),
                ('estadoCapacidad', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.estado')),
                ('playa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.playas')),
            ],
        ),
        migrations.CreateModel(
            name='Sombrillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.estado')),
                ('subPlaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.subplayas')),
            ],
        ),
        migrations.CreateModel(
            name='SombrillaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.grupousuarios')),
                ('sombrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.sombrillas')),
            ],
        ),
        migrations.CreateModel(
            name='Objetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=53)),
                ('cantidad', models.IntegerField()),
                ('alquilados', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imageObj', models.URLField(blank=True, default='https://i.ibb.co/mFknmDH/objetos-default.jpg', null=True)),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('edificioInteres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.edificiosinteres')),
            ],
        ),
        migrations.AddField(
            model_name='grupousuarios',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.usuarios'),
        ),
        migrations.CreateModel(
            name='EdificiosPlaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.playas')),
                ('nombreEI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.edificiosinteres')),
            ],
        ),
        migrations.AddField(
            model_name='edificiosinteres',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.estado'),
        ),
        migrations.AddField(
            model_name='edificiosinteres',
            name='tipoEdificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.tiposedificio'),
        ),
        migrations.CreateModel(
            name='EAlimentoBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('estadoCapacidad', models.IntegerField()),
                ('edificioInteres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.edificiosinteres')),
            ],
        ),
        migrations.CreateModel(
            name='AreasPlaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.areas')),
                ('edificioPlaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.edificiosplaya')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.trabajadores')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='edificioInteres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playa.edificiosinteres'),
        ),
    ]
