# Generated by Django 3.2.4 on 2021-06-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplayas',
            name='imgSubPlaya',
            field=models.URLField(default='https://i.ibb.co/dQn81QZ/playa-default.png', null=True),
        ),
    ]
