# Generated by Django 3.2.4 on 2021-06-29 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playa', '0002_subplayas_imgsubplaya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetos',
            old_name='edificioInteres',
            new_name='nombreEI',
        ),
    ]
